name: deploy_to_firebase_hosting



on:

  push:

    branches: [ master ]




jobs:

  deploy_to_firebase_hosting:



    runs-on: ubuntu-latest

    

    steps:

      # - name: Checkout the repository

      #   uses: actions/checkout@master
      
      # - name: Deploy to Firebase

      #   uses: w9jds/firebase-action@master

      #   with:

      #     args: deploy --only hosting
      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: get commit message
        run: |
           echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: show commit message
        run : echo $commitmsg

      - name: IFTTT Webhook
        uses: alfredosalzillo/ifttt-webhook-action@v1
        with:
          event: github
          key: gE6jSCuBiANWubHmXlSuA
          value1:  ${{env.commitmsg}}
          value2: commitmsg
          value3: none
      

        env:
          NAME: Syllabus
          FIREBASE_TOKEN: ${{ secrets.TEST_TOKEN }}
        
