name: deploy_to_firebase_hosting



on:

  push:

    branches: [ master ]




jobs:

  deploy_to_firebase_hosting:



    runs-on: ubuntu-latest

    

    steps:

      - name: Checkout the repository

        uses: actions/checkout@master
      - name: IFTTT Webhook
        uses: alfredosalzillo/ifttt-webhook-action@v1
        with:
          event: github
          key: gE6jSCuBiANWubHmXlSuA
          value1:  ${{env.GITHUB_REPOSITORY}}
          value2: commitmsg
          value3: none
      

      - name: Deploy to Firebase

        uses: w9jds/firebase-action@master

        with:

          args: deploy --only hosting

        env:

          FIREBASE_TOKEN: ${{ secrets.TEST_TOKEN }}
