name: deploy_to_firebase_hosting



on:

  push:

    branches: [ master ]




jobs:

  deploy_to_firebase_hosting:



    runs-on: ubuntu-latest

    

    steps:

      # - name: Checkout the repository

      #   uses: actions/checkout@master
      
      # - name: Deploy to Firebase

      #   uses: w9jds/firebase-action@master

      #   with:

      #     args: deploy --only hosting
      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ github.message }}
        run: echo "$GITHUB_CONTEXT"

      # - name: IFTTT Webhook
      #   env:
      #     NAME: Syllabus
      #     this: ONE
      #     FIREBASE_TOKEN: ${{ secrets.TEST_TOKEN }}
      #   uses: alfredosalzillo/ifttt-webhook-action@v1
      #   with:
      #     event: github
      #     key: gE6jSCuBiANWubHmXlSuA
      #     value1:  ${{env.GITHUB_CONTEXT}} AND ${{env.this}}
      #     value2: commitmsg
      #     value3: none
      

        
