name: deploy_to_firebase_hosting



on:

  push:

    branches: [ master ]




jobs:

  deploy_to_firebase_hosting:



    runs-on: ubuntu-latest

    

    steps:

      # - name: Checkout the repository

      #   uses: actions/checkout@master
      
      # - name: Deploy to Firebase

      #   uses: w9jds/firebase-action@master

      #   with:

      #     args: deploy --only hosting


      - name: IFTTT Webhook
        uses: alfredosalzillo/ifttt-webhook-action@v1
        with:
          event: github
          key: gE6jSCuBiANWubHmXlSuA
          value1:  ${{env.GITHUB_CONTEXT.repository}} AND ${{env.stupid}}
          value2: commitmsg
          value3: none
      

        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          stupid: AHHHH
          NAME: Syllabus
          FIREBASE_TOKEN: ${{ secrets.TEST_TOKEN }}
        run: echo "$GITHUB_CONTEXT"
        
