name: deploy_to_firebase_hosting



on:

  push:

    branches: [ master ]




jobs:

  deploy_to_firebase_hosting:



    runs-on: ubuntu-latest

    

    steps:

      - name: Checkout the repository

        uses: actions/checkout@master
      
      - name: Deploy to Firebase

        uses: w9jds/firebase-action@master

        with:

          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.TEST_TOKEN }}

      # - name : GITHUB CONTEXT
      #   env:
      #     msg: ${{ toJSON(github.event.commits[0].message) }}
      #   run: echo "${{env.msg}}"

      - name: IFTTT Webhook
        uses: alfredosalzillo/ifttt-webhook-action@v1
        with:
          event: github
          key: gE6jSCuBiANWubHmXlSuA
          value1: ${{toJSON(github.event.repository.name)}}
          value2: ${{toJSON(github.event.commits[0].message)}}
          value3: ${{toJSON(github.event.repository.html_url)}}
      

        
